permissions:
- nucleus.suicide.exempt.*
- inspector.toggle
- nucleus.teleport.tpahere.exempt.cost
- inspector.use
- nucleus.teleport.tpahere.base
- nucleus.home.list.base
- nucleus.home.base
- nucleus.spawn.exempt.cost
- nucleus.teleport.tpa.exempt.cost
- nucleus.teleport.tpaccept.base
- nucleus.home.set.base
- nucleus.teleport.tpa.base
- nucleus.hat.base
- nucleus.spawn.base
- nucleus.warp.base
- nucleus.home.set.exempt.*
- nucleus.teleport.teleport.exempt.cost
- nucleus.home.exempt.cost
default: true
